version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.5

    working_directory: ~/repo

    steps:
      - run: sudo apt install -y rsync
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-


      # vue-test-utils is installed from github for now and the circleci git config
      # rewrites the https: url to git: by default, so we remove it here
      # once vue-test-utils is published properly we can remove this
      - run: git config --global --remove-section url."ssh://git@github.com"
      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test --ci --testResultsProcessor="jest-junit"
      - run: bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: junit.xml

      - run: yarn lint
      - run: yarn build
      - run: yarn build-storybook

      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "quasar" ]; then
              ./deploy.sh "${CIRCLE_BRANCH}" "${CIRCLE_BRANCH}"
            elif [ ! -z "${CIRCLE_TAG}" ]; then
              ./deploy.sh "${CIRCLE_TAG}" release
            fi
