defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.5

tag-filter: &tag-filter
  tags:
    only: /^quasar-v.*/

default-workflow-job: &default-workflow-job  
  filters:
    <<: *tag-filter
  requires:
    - install-dependencies

version: 2
jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn test --ci --runInBand
      - run: bash <(curl -s https://codecov.io/bash)

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn lint

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist

  build-storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn build-storybook
      - persist_to_workspace:
          root: ~/repo
          paths:
            - storybook-static

  deploy-branch:
    <<: *defaults
    steps:
      - run: sudo apt install -y rsync
      - checkout
      - attach_workspace:
          at: ~/repo
      - deploy:
          name: Dev Branch Deploy
          command: |
            ./deploy.sh "${CIRCLE_BRANCH}" "${CIRCLE_BRANCH}"

  deploy-release:
    <<: *defaults
    steps:
      - run: sudo apt install -y rsync
      - checkout
      - attach_workspace:
          at: ~/repo
      - deploy:
          name: Release Deploy
          command: |
            ./deploy.sh "${CIRCLE_BRANCH}" release

workflows:
  version: 2
  all-the-things:
    jobs:
      - install-dependencies
      - test:
          <<: *default-workflow-job
      - lint:
          <<: *default-workflow-job
      - build:
          <<: *default-workflow-job
      - build-storybook:
          <<: *default-workflow-job
      - deploy-branch:
          #
          # specific branches are deployed in their own "<branch>" directory
          #
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - lint
            - build
            - build-storybook
      - deploy-release:
          #
          # deploy quasar-release branch "release" directory
          #
          filters:
            <<: *tag-filter
            branches:
              ignore: /.*/
          requires:
            - test
            - lint
            - build
            - build-storybook
