tag-filter: &tag-filter
  tags:
    only: /^quasar-.*/

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.5
  filters:
    <<: *tag-filter

version: 2
jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn test --ci
      - run: bash <(curl -s https://codecov.io/bash)

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn lint

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist

  build-storybook:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn build-storybook
      - persist_to_workspace:
          root: ~/repo
          paths:
            - storybook-static

  deploy-branch:
    <<: *defaults
    steps:
      - run: sudo apt install -y rsync
      - checkout
      - attach_workspace:
          at: ~/repo
      - deploy:
          name: Dev Branch Deploy
          command: |
            ./deploy.sh "${CIRCLE_BRANCH}" "${CIRCLE_BRANCH}"

  deploy-tag:
    <<: *defaults
    steps:
      - run: sudo apt install -y rsync
      - checkout
      - attach_workspace:
          at: ~/repo
      - deploy:
          name: Release Tag Deploy
          command: |
            ./deploy.sh "${CIRCLE_TAG}" release

workflows:
  version: 2
  all-the-things:
    jobs:
      - install-dependencies
      - test:
          filters:
            <<: *tag-filter
          requires:
            - install-dependencies
      - lint:
          filters:
            <<: *tag-filter
          requires:
            - install-dependencies
      - build:
          filters:
            <<: *tag-filter
          requires:
            - install-dependencies
      - build-storybook:
          filters:
            <<: *tag-filter
          requires:
            - install-dependencies
      - deploy-branch:
          #
          # specific dev branches are deployed in their own "<branch>" directory
          #
          filters:
            branches:
              only:
                - quasar
          requires:
            - test
            - lint
            - build
            - build-storybook
      - deploy-tag:
          #
          # all "quasar-*" tags are considered releases and go into "release" directory
          #
          filters:
            <<: *tag-filter
            branches:
              ignore: /.*/
          requires:
            - test
            - lint
            - build
            - build-storybook
